model:
  input_len: 66
  strand: "ss"
  task: "binary_classification"
  aggr: None
  fc_kwargs: 
    hidden_dims: [128, 64]
    dropout_rate: 0.2
    batchnorm: True
    output_dim: 1
    
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: "val_loss"
        mode: "min"
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: "/cellar/users/aklie/projects/EUGENE/results/simple/classification" 
      name: "ssFCN"
      version: "2022_04_23_NPY_Baseline"
  gpus: 1
  max_epochs: 100
  
data:
  seq_file: "/cellar/users/aklie/projects/EUGENE/data/2021_OLS_Library/ohe_seq/0.09-0.4_X-training_ohe-seq.npy"
  batch_size: 1024
  num_workers: 4
  transform:
    - class_path: eugene.utils.seq_transforms.ToTensor
      init_args:
        transpose: True
  split: 0.9
  load_kwargs: 
    rev_seq_file: "/cellar/users/aklie/projects/EUGENE/data/2021_OLS_Library/ohe_seq/0.09-0.4_X-training_ohe-seq-rev.npy"
    target_file: "/cellar/users/aklie/projects/EUGENE/data/2021_OLS_Library/binary/0.09-0.4_y-training_binary.txt"
    is_target_text: True