ckpt_path: "/cellar/users/aklie/projects/EUGENE/results/eugene/0.09-0.4/dsEUGENE/2022_04_06_test/checkpoints/epoch=9-step=1739.ckpt"

trainer:
  logger: false
  callbacks:
    - class_path: eugene.utils.custom_callbacks.PredictionWriter
      init_args:
        output_dir: "/cellar/users/aklie/projects/EUGENE/results/eugene/0.09-0.4/dsEUGENE/2022_04_06_test/"
        write_interval: "epoch"
        prefix: "All_Genomic_Sequences_"
  gpus: 1
  
model:
  conv_kwargs:
    input_len: 66
    channels: [4, 32, 64]
    conv_kernels: [15, 5]
    pool_kernels: [2, 1]
    dropout_rates: 0.2
    batchnorm: True
  rnn_kwargs: 
    output_dim: 64
    batch_first: True
  fc_kwargs: 
    hidden_dims: [32]
    batchnorm: True
    output_dim: 1
  learning_rate: 0.001
  
data:
  seq_file: "/cellar/users/aklie/projects/EUGENE/data/All_Genomic_Sequences/All_Genomic_Sequences.tsv"
  test: True
  load_kwargs: 
    seq_col: "SEQ"