model:
  input_len: 66
  strand: "ds"
  task: "regression"
  aggr: None
  conv_kwargs:
    channels: [4, 32, 64]
    conv_kernels: [15, 5]
    pool_kernels: [2, 1]
    dropout_rates: 0.2
    batchnorm: True
  fc_kwargs: 
    hidden_dims: [1536]
    dropout_rate: 0.2
    batchnorm: True
    output_dim: 1